Push all semver versions to Docker Hub
For example, if a commit is tagged 2.3.4, then we will try to push the
images NAME:2.3.4, NAME:2.3 and NAME:2.

A git tag must match "version" in package.json.

diff --git a/.travis/docker_login_tag_push b/.travis/docker_login_tag_push
--- a/.travis/docker_login_tag_push
+++ b/.travis/docker_login_tag_push
@@ -2,13 +2,13 @@
 
 set -u
 
-[ "$#" -ne 2 ] && {
-  echo "Usage: $(basename "$0") SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]" 1>&2
+[ "$#" -lt 2 ] && {
+  echo "Usage: $(basename "$0") SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]..." 1>&2
   exit 1
 }
 
 SOURCE_IMAGE_TAG="$1"
-TARGET_IMAGE_TAG="$2"
+shift 1
 IS_DOCKER_HUB_AVAILABLE="$(if [ -z ${DOCKER_USERNAME+foo} ]; then
                              echo 'false'
                            else
@@ -18,7 +18,24 @@ IS_DOCKER_HUB_AVAILABLE="$(if [ -z ${DOCKER_USERNAME+foo} ]; then
 if [ "${IS_DOCKER_HUB_AVAILABLE}" = true ]; then
   # Avoid a warning from docker login by using --password-stdin.
   echo "${DOCKER_PASSWORD}" \
-    | docker login --username="${DOCKER_USERNAME}" --password-stdin \
-  && docker tag "${SOURCE_IMAGE_TAG}" "${TARGET_IMAGE_TAG}" \
-  && docker push "${TARGET_IMAGE_TAG}"
+    | docker login --username="${DOCKER_USERNAME}" --password-stdin
+  if [ $? -ne 0 ]; then
+    echo "docker login failed with exit status $?" 1>&2
+    exit 1
+  fi
+  echo "Info: Push the following images to Docker Hub: $*" 1>&2
+  for TARGET in "$@"; do
+    docker tag "${SOURCE_IMAGE_TAG}" "${TARGET}"
+    if [ $? -ne 0 ]; then
+      echo "docker tag failed with exit status $?" 1>&2
+      exit 1
+    fi
+    docker push "${TARGET}"
+    if [ $? -ne 0 ]; then
+      echo "docker push failed with exit status $?" 1>&2
+      exit 1
+    fi
+  done
+else
+  echo "Info: DOCKER_USERNAME or DOCKER_PASSWORD is not set" 1>&2
 fi
